
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 18 23:12:01 CST 2020
//----------------------------------------------------

package practica1compi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 28;
  public static final int EXTENSION_CSV = 15;
  public static final int PUNTO = 5;
  public static final int PUNTOYCOMA = 19;
  public static final int INSERTAR = 22;
  public static final int PCERRADO = 31;
  public static final int OR = 29;
  public static final int IGUAL = 12;
  public static final int MENOR_IGUAL = 16;
  public static final int ELIMINAR = 25;
  public static final int ERROR = 33;
  public static final int MAYOR_IGUAL = 17;
  public static final int UBICACION = 10;
  public static final int MAYOR_QUE = 3;
  public static final int COMILLAS = 13;
  public static final int PROYECTO = 4;
  public static final int POR = 7;
  public static final int FILTRAR = 21;
  public static final int VALORES = 26;
  public static final int ASIGNAR = 24;
  public static final int ACTUALIZAR = 23;
  public static final int COMA = 6;
  public static final int MENOR_QUE = 2;
  public static final int NOMBRE = 11;
  public static final int EOF = 0;
  public static final int DIFERENTE = 18;
  public static final int IDNOMBRE = 32;
  public static final int error = 1;
  public static final int DIAGONAL = 14;
  public static final int PABIERTO = 30;
  public static final int ARCHIVO = 8;
  public static final int EN = 27;
  public static final int CARPETA = 9;
  public static final int PATH = 34;
  public static final int SELECCIONAR = 20;
}

